#!/bin/sh
#
# Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# This file is in the public domain.

${XXD:-xxd} -g2 |
sed -e '
	s/^[^ ]* //	# remove leading spaces
	s/^.\{40\}/&|/	# put a "|" after 40 columns
	s/[ ]*$//	# remove trailing spaces
'
