#!/bin/sh
#
# Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# This file is in the public domain.

# Decode a hexdump from the test suite and output the raw binary
sed -e '
	/^[ ]*$/d	# remove blank lines
	/^[ ]*#/d	# remove comment lines
	s/|.*//		# remove ASCII display
' |
${XXD:-xxd} -r -p
