#!/bin/sh

set -e
set -u

ROOT_DIR=$(dirname "$0")

test -n "$ROOT_DIR"

autoreconf -i "$ROOT_DIR"

"$ROOT_DIR"/configure \
	--enable-maintainer-mode \
	--enable-warnings \
	--enable-hardening \
	--enable-silent-rules \
	--with-dotnet \
	"$@"
