#!/bin/sh

set -e
set -u

WORK_DIR=$(pwd)
ROOT_DIR=$(dirname "$0")

test -n "$ROOT_DIR"
cd "$ROOT_DIR"

autoreconf -i

cd "$WORK_DIR"
"$ROOT_DIR"/configure \
	--enable-warnings \
	--enable-hardening \
	--enable-silent-rules \
	--with-documentation \
	"$@"
